[workspace]
members = ["kic-trigger-flow", "trigger-flow-manager"]
resolver = "2"

[workspace.dependencies]
trigger-flow-manager = {path = "trigger-flow-manager"}
kic-trigger-flow = {path = "kic-trigger-flow"}
indexmap = { version = "2.13.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde-saphyr = "0.0.21"


[workspace.package]
version = "0.1.0"

[workspace.lints.rust]
warnings = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)', 'cfg(coverage)'] }

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
undocumented_unsafe_blocks = "deny"
arithmetic_side_effects = "deny"

[workspace.lints.rustdoc]
all = "warn"
missing_doc_code_examples = "warn"
