[package]
name = "kic-trigger-flow"
version = {workspace = true}
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-cors = "0.7.1"
actix-web = "4.12.1"
actix-files = "0.6"
actix-ws = "0.3.0"
futures = "0.3"
anyhow = "1.0.100"
serde = "1.0.228"
tokio = "1.49.0"
trigger-flow-manager = { workspace = true }
